palette:
  hydro: "#0072B2"
  nuclear: "#E69F00"
  biofuel: "#009E73"
  thermal_gas: "#56B4E9"
  thermal_fuel: "#D55E00"
  slack_pos: "#999999"
  slack_neg: "#CC79A7"
  demand_response: "#F0E442"
  curtail: "#999999"
  storage_charge: "#CC79A7"
  storage_discharge: "#0072B2"
  imports: "#56B4E9"
  exports: "#D55E00"
  net: "#009E73"
