# Cost parameters: adjusted for 2022 full-year analysis with half-hourly resolution
costs:
  dispatch: 50.0  # EUR/MWh base cost
  storage: 10.0   # EUR/MWh
  demand_response: 100.0  # EUR/MWh
  exchange: 15.0  # EUR/MWh - encourages inter-regional exchanges
  storage_charge: 8.0   # EUR/MWh - separate cost for charging
  storage_discharge: 5.0  # EUR/MWh - separate cost for discharging
  transport_exchange: 12.0  # EUR/MWh - cost for transportation grid exchanges
  slack_penalty: 1000.0  # EUR/MWh - high penalty for using slack variables

# Global constraints applied to all regions unless overridden
constraints:
  storage_capacity: 3000.0  # MWh - INCREASED from 1000.0 to handle larger variations in net load
  storage_efficiency: 0.995  # Self-discharge efficiency (per half-hour)
  charge_efficiency: 0.90   # Efficiency when charging storage
  discharge_efficiency: 0.90 # Efficiency when discharging storage
  exchange_capacity: 2000.0  # MW - INCREASED from 800.0 to allow more flexibility in power flow between regions
  transport_capacity: 1200.0  # MW - INCREASED from 500.0 to allow more flexibility with transportation grid
  initial_storage_level: 0.5 # INCREASED from 0.3 to start with 50% of storage capacity
  max_slack: 2000.0         # INCREASED from 500.0 to allow more flexibility in balance constraints
  max_dispatch: 8000.0     # INCREASED from 5000.0 to handle potential high net load values
  min_dispatch: 0.0        # Minimum dispatch per region (MW)
  max_demand_response: 500.0  # INCREASED from 300.0 to allow more demand response flexibility
  max_daily_demand_response: 2000.0  # INCREASED from 1000.0 to allow more daily flexibility
  max_total_flexibility: 10000.0  # INCREASED from 6000.0 to permit greater overall flexibility
  # NEW ramping constraints to allow more gradual changes in dispatch
  max_ramp_up: 1000.0      # Maximum increase in dispatch between time periods (MW/period)
  max_ramp_down: 1000.0    # Maximum decrease in dispatch between time periods (MW/period)

# List of regions in the analysis
regions:
  - Auvergne Rhone Alpes
  - Nouvelle Aquitaine
  - Occitanie
  - Provence Alpes Cote d'Azur

# Region-specific constraints and parameters to address regional imbalances
regional_constraints:
  "Provence Alpes Cote d'Azur":
    storage_capacity: 5000.0  # INCREASED from 2000.0 to handle larger variations in net load
    dispatch_cost_multiplier: 1.1  # 10% higher dispatch cost to encourage storage use
    max_slack: 3000.0  # ADDED higher slack allowance for this specific region
  
  "Nouvelle Aquitaine":
    storage_capacity: 4000.0  # INCREASED from 1500.0 to handle larger variations
    max_slack: 2500.0  # ADDED higher slack allowance for this specific region
    
  "Auvergne Rhone Alpes":
    storage_capacity: 4500.0  # ADDED increased storage capacity for this region
    max_slack: 2500.0  # ADDED higher slack allowance
    
  "Occitanie":
    storage_capacity: 3500.0  # ADDED increased storage capacity for this region
    max_slack: 2500.0  # ADDED higher slack allowance

# Data quality parameters
data_quality:
  replace_nan_value: 1000.0  # Default value for NaN/Inf in net_load
  max_net_load: 50000.0     # INCREASED from 30000.0 to allow for higher peak loads
  min_net_load: -20000.0    # DECREASED from -10000.0 to allow for more negative net load (e.g., high renewable generation)
  smoothing_window: 5       # INCREASED from 3 to provide more smoothing for erratic data
  outlier_threshold: 3.0    # ADDED standard deviation threshold for detecting outliers
  interpolation_method: 'linear'  # ADDED method for interpolating missing values

paths:
  data_dir: "data"
  output_dir: "outputs"
  
# Time settings for simulation
time_settings:
  resolution: "30min"  # Half-hour time steps
  start_date: "2021-01-01"  # Start of simulation period
  end_date: "2021-12-31"  # End of simulation period
  
# Analysis settings
analysis:
  seasonal_breakdown: true  # Generate seasonal analysis
  daily_patterns: true  # Analyze daily patterns
  yearly_overview: true  # Create yearly overview charts
  comprehensive_report: true  # Generate comprehensive PDF report
